<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Asisten extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Asisten_model');
    }

    /*
     * Listing of tb_barang
     */
    function index()
    {
        if ($this->session->userdata("level")!=NULL) {
            $jumlah_data = $this->Asisten_model->jumlah_data();
            $config['base_url'] = base_url() . 'asisten/index/';
            $config['total_rows'] = $jumlah_data;
            $config['per_page'] = 10;

            // Pagination link format 
            $config['num_tag_open'] = '<li>';
            $config['num_tag_close'] = '</li>';
            $config['cur_tag_open'] = '<li class="active"><a href="javascript:void(0);">';
            $config['cur_tag_close'] = '</a></li>';
            $config['next_link'] = 'Next';
            $config['prev_link'] = 'Prev';
            $config['next_tag_open'] = '<li class="pg-next">';
            $config['next_tag_close'] = '</li>';
            $config['prev_tag_open'] = '<li class="pg-prev">';
            $config['prev_tag_close'] = '</li>';
            $config['first_tag_open'] = '<li>';
            $config['first_tag_close'] = '</li>';
            $config['last_tag_open'] = '<li>';
            $config['last_tag_close'] = '</li>';

            $from = $this->uri->segment(3);
            $this->pagination->initialize($config);
            $data['asisten'] = $this->Asisten_model->get_all_asisten($config['per_page'], $from);
            // $data['barang'] = $this->Barang_model->get_all_barang();

            $data['_view'] = 'asisten/index';
            if ($this->session->userdata("level") == 'admin') {
                $this->load->view('layouts/main', $data);
            } else {
                $this->load->view('layouts/main_user', $data);
            }
        } else {
            $this->load->view('login/login');
        }
    }
    
    private function _uploadImage()
    {
        $config['upload_path']          = 'resources/img/';
        $config['allowed_types']        = 'gif|jpg|png';
        $config['file_name']            = $this->input->post('id_asisten') . '-' . $this->input->post('nm_asisten');
        $config['overwrite']            = true;
        $config['max_size']             = 1024; // 1MB
       $this->load->library('upload', $config);
        if ($this->upload->do_upload('img')) {
            return $this->upload->data('file_name');
        }

        return null;
    }
    /*
     * Adding a new tb_barang
     */
    function add()
    {
        if (isset($_POST) && count($_POST) > 0) {
            $params = array(
                'id_asisten' => $this->input->post('id_asisten'),
                'nm_asisten' => $this->input->post('nm_asisten'),
                'addrs_asisten' => $this->input->post('addrs_asisten'),
                'telp_asisten' => $this->input->post('telp_asisten'),
                'img' =>  $this->_uploadImage()
            );

            $id_asisten = $this->Asisten_model->add_asisten($params);
            redirect('asisten/index');
        } else {
            $data['_view'] = 'asisten/add';
            if ($this->session->userdata("level") == 'admin') {
                $this->load->view('layouts/main', $data);
            } else {
                $this->load->view('layouts/main_user', $data);
            }
        }
    }

    /*
     * Editing a tb_barang
     */
    function edit($id_asisten)
    {
        // check if the tb_barang exists before trying to edit it
        $data['asisten'] = $this->Asisten_model->get_asisten($id_asisten);

        if (isset($data['asisten']['id_asisten'])) {
            if (isset($_POST) && count($_POST) > 0) {
                $params = array(
                    'id_asisten' => $this->input->post('id_asisten'),
                    'nm_asisten' => $this->input->post('nm_asisten'),
                    'addrs_asisten' => $this->input->post('addrs_asisten'),
                    'telp_asisten' => $this->input->post('telp_asisten'),
                    'img' =>  $this->_uploadImage()
                );

                $this->Asisten_model->update_asisten($id_asisten, $params);
                redirect('asisten/index');
            } else {
                $data['_view'] = 'asisten/edit';
                if ($this->session->userdata("level") == 'admin') {
                $this->load->view('layouts/main', $data);
            } else {
                $this->load->view('layouts/main_user', $data);
            }
            }
        } else
            show_error('The asisten you are trying to edit does not exist.');
    }

    /*
     * Deleting tb_barang
     */
    function remove($id_asisten)
    {
        $asisten = $this->Asisten_model->get_asisten($id_asisten);

        // check if the tb_barang exists before trying to delete it
        if (isset($asisten['id_asisten'])) {
            $this->Asisten_model->delete_asisten($id_asisten);
            redirect('asisten/index');
        } else
            show_error('The asisten you are trying to delete does not exist.');
    }
}
