<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Barang_keluar extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Barang_keluar_model');
    }

    /*
     * Listing of barang
     */
    function index()
    {
        if ($this->session->userdata("level")!=NULL) {
            $data['barang_keluar'] = $this->Barang_keluar_model->get_all_Barang_keluar();

            $data['_view'] = 'barang_keluar/index';
            if ($this->session->userdata("level") == 'admin') {
                $this->load->view('layouts/main', $data);
            } else {
                $this->load->view('layouts/main_user', $data);
            }
        } else {
            $this->load->view('login/login');
        }
    }

    /*
     * Adding a new Barang_keluar
     */

    function add()
    {
        if (isset($_POST) && count($_POST) > 0) {
            $params = array(
                'id_inventaris' => $this->input->post('id_inventaris'),
                'id_barang' => $this->input->post('id_barang'),
                'ket_kondisi' => $this->input->post('ket_kondisi'),
                'id_ruangan' => $this->input->post('id_ruangan'),
                'tgl_keluar' => $this->input->post('tgl_keluar')
            );
            $Barang_keluar_id = $this->Barang_keluar_model->add_Barang_keluar($params);
            redirect('barang_keluar/index');
        } else {
            $data['ruangan'] = $this->Barang_keluar_model->get_all_ruangan();
            $data['barang'] = $this->Barang_keluar_model->get_all_barang();
            $data['_view'] = 'barang_keluar/add';
            if ($this->session->userdata("level") == 'admin') {
                $this->load->view('layouts/main', $data);
            } else {
                $this->load->view('layouts/main_user', $data);
            }
        }
    }

    /*
     * Editing a Barang_keluar
     */
    function edit($id_Barang_keluar)
    {
        // check if the Barang_keluar exists before trying to edit it
        $data['barang_keluar'] = $this->Barang_keluar_model->get_Barang_keluar($id_Barang_keluar);

        if (isset($data['barang_keluar']['id'])) {
            if (isset($_POST) && count($_POST) > 0) {
                $params = array(
                    'id_inventaris' => $this->input->post('id_inventaris'),
                    'id_barang' => $this->input->post('id_barang'),
                    'ket_kondisi' => $this->input->post('ket_kondisi'),
                    'id_ruangan' => $this->input->post('id_ruangan'),
                    'tgl_keluar' => $this->input->post('tgl_keluar')
                );

                $this->Barang_keluar_model->update_Barang_keluar($id_Barang_keluar, $params);
                redirect('barang_keluar/index');
            } else {
                $data['ruangan'] = $this->Barang_keluar_model->get_all_ruangan();
                $data['barang'] = $this->Barang_keluar_model->get_all_barang();
                $data['_view'] = 'barang_keluar/edit';
                if ($this->session->userdata("level") == 'admin') {
                $this->load->view('layouts/main', $data);
            } else {
                $this->load->view('layouts/main_user', $data);
            }
            }
        } else
            show_error('The Barang_keluar you are trying to edit does not exist.');
    }

    /*
     * Deleting Barang_keluar
     */
    function remove($id_Barang_keluar)
    {
        $Barang_keluar = $this->Barang_keluar_model->get_Barang_keluar($id_Barang_keluar);

        // check if the Barang_keluar exists before trying to delete it
        if (isset($Barang_keluar['id'])) {
            $this->Barang_keluar_model->delete_Barang_keluar($id_Barang_keluar);
            redirect('barang_keluar/index');
        } else
            show_error('The Barang_keluar you are trying to delete does not exist.');
    }
}
