<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Barang extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Barang_model');
        $this->load->library('pdf');
    }

    /*
     * Listing of barang
     */
    function index()
    {
        if ($this->session->userdata("level") != NULL) {
            $jumlah_data = $this->Barang_model->jumlah_data();
            $config['base_url'] = base_url() . 'barang/index/';
            $config['total_rows'] = $jumlah_data;
            $config['per_page'] = 5;

            // Pagination link format 
            $config['num_tag_open'] = '<li>';
            $config['num_tag_close'] = '</li>';
            $config['cur_tag_open'] = '<li class="active"><a href="javascript:void(0);">';
            $config['cur_tag_close'] = '</a></li>';
            $config['next_link'] = 'Next';
            $config['prev_link'] = 'Prev';
            $config['next_tag_open'] = '<li class="pg-next">';
            $config['next_tag_close'] = '</li>';
            $config['prev_tag_open'] = '<li class="pg-prev">';
            $config['prev_tag_close'] = '</li>';
            $config['first_tag_open'] = '<li>';
            $config['first_tag_close'] = '</li>';
            $config['last_tag_open'] = '<li>';
            $config['last_tag_close'] = '</li>';

            $from = $this->uri->segment(3);
            $this->pagination->initialize($config);
            $data['barang'] = $this->Barang_model->get_all_barang($config['per_page'], $from);
            // $data['barang'] = $this->Barang_model->get_all_barang();

            $data['_view'] = 'barang/index';
            if ($this->session->userdata("level") == 'admin') {
                $this->load->view('layouts/main', $data);
            } else {
                $this->load->view('layouts/main_user', $data);
            }
        } else {
            $this->load->view('login/login');
        }
    }

    function search()
    {
        $keyword = $this->input->post('search');
        $jumlah_data = $this->Barang_model->jumlah_data_by($keyword);
        $config['base_url'] = base_url() . 'barang/index/';
        $config['total_rows'] = $jumlah_data;
        $config['per_page'] = 5;

        // Pagination link format 
        $config['num_tag_open'] = '<li>';
        $config['num_tag_close'] = '</li>';
        $config['cur_tag_open'] = '<li class="active"><a href="javascript:void(0);">';
        $config['cur_tag_close'] = '</a></li>';
        $config['next_link'] = 'Next';
        $config['prev_link'] = 'Prev';
        $config['next_tag_open'] = '<li class="pg-next">';
        $config['next_tag_close'] = '</li>';
        $config['prev_tag_open'] = '<li class="pg-prev">';
        $config['prev_tag_close'] = '</li>';
        $config['first_tag_open'] = '<li>';
        $config['first_tag_close'] = '</li>';
        $config['last_tag_open'] = '<li>';
        $config['last_tag_close'] = '</li>';

        $from = $this->uri->segment(3);
        $this->pagination->initialize($config);
        $data['barang'] = $this->Barang_model->search($config['per_page'], $from, $keyword);
        // $data['barang'] = $this->Barang_model->get_all_barang();

        $data['_view'] = 'barang/index';
        if ($this->session->userdata("level") == 'admin') {
            $this->load->view('layouts/main', $data);
        } else {
            $this->load->view('layouts/main_user', $data);
        }
    }

    function cetak()
    {
        $tgl_awal = $this->input->post('tgl_awal');
        $tgl_ahir = $this->input->post('tgl_ahir');
        if ($tgl_awal != 0) {
            $pdf = new FPDF('P', 'mm', 'A4');
            // membuat halaman baru
            $pdf->AddPage();
            // setting jenis font yang akan digunakan
            $pdf->SetFont('Arial', 'B', 16);
            // mencetak string 
            $pdf->SetFont('Arial', 'B', 14);
            $pdf->Image('resources/img/poltek.png', 10, 6, 28);
            $pdf->Cell(190, 7, 'UPT SISTEM INFORMASI', 0, 1, 'C');
            $pdf->SetFont('Arial', 'B', 18);
            $pdf->Cell(190, 7, 'POLITEKNIK HARAPAN BERSAMA TEGAL', 0, 1, 'C');
            $pdf->SetFont('Arial', 'B', 12);
            $pdf->Cell(190, 7, 'LAPORAN BARANG', 0, 1, 'C');
            $pdf->SetFont('Arial', '', 9);
            $pdf->Cell(190, 6, 'Periode ' . date('d-m-Y', strtotime($tgl_awal)) . ' s/d ' . date('d-m-Y', strtotime($tgl_ahir)), 0, 1, 'C');

            // Memberikan space kebawah agar tidak terlalu rapat
            $pdf->Ln();
            $pdf->Cell(10, 7, '', 0, 1);
            $pdf->SetFont('Arial', 'B', 9);
            $pdf->Cell(10, 8, 'NO.', 1, 0, 'C');
            $pdf->Cell(40, 8, 'NAMA BARANG', 1, 0);
            $pdf->Cell(35, 8, 'KATEGORI', 1, 0);
            $pdf->Cell(30, 8, 'MERK', 1, 0);
            $pdf->Cell(30, 8, 'LOKASI', 1, 0);
            $pdf->Cell(15, 8, 'STOK', 1, 0, 'C');
            $pdf->Cell(30, 8, 'TGL. MASUK', 1, 1, 'C');
            $pdf->SetFont('Arial', '', 9);

            $barang = $this->db->select('*');
            $barang = $this->db->from('barang a');
            $barang = $this->db->join('kategori b', 'b.id_kategori=a.id_kategori', 'left');
            $barang = $this->db->join('merk c', 'c.id_merk=a.id_merk', 'left');
            $barang = $this->db->join('satuan d', 'd.id_satuan=a.id_satuan', 'left');
            $barang = $this->db->join('ruangan e', 'e.id_ruangan=a.id_ruangan', 'left');
            $barang = $this->db->where('a.tgl_masuk BETWEEN "' . date('Y-m-d', strtotime($tgl_awal)) . '" and "' . date('Y-m-d', strtotime($tgl_ahir)) . '"');
            $barang = $this->db->order_by('a.id_barang', 'asc');
            $barang = $this->db->get()->result();
            $X = 0;
            foreach ($barang as $row) {
                $X += 1;
                $pdf->Cell(10, 6, $X, 1, 0, 'C');
                $pdf->Cell(40, 6, $row->nm_barang, 1, 0);
                $pdf->Cell(35, 6, $row->nm_kategori, 1, 0);
                $pdf->Cell(30, 6, $row->nm_merk, 1, 0);
                $pdf->Cell(30, 6, $row->nm_ruangan, 1, 0);
                $pdf->Cell(15, 6, $row->stok, 1, 0, 'C');
                $pdf->Cell(30, 6, date("d-m-Y", strtotime($row->tgl_masuk)), 1, 1, 'C');
            }
            $pdf->Output();
        } else {
            $data['_view'] = 'barang/cetak';
            if ($this->session->userdata("level") == 'admin') {
                $this->load->view('layouts/main', $data);
            } else {
                $this->load->view('layouts/main_user', $data);
            }
        }
    }

    function get_merk_kat()
    {
        // load model dan form helper
        if ($id_kat = $this->input->post('id')) {
            $data = $this->Barang_model->get_merk_kat($id_kat);
            // $this->load->view('barang',$kategori);
            echo json_encode($data);
        }
    }

    function get_all_kategori()
    {
        // load model dan form helper
        $data['kat'] = $this->Barang_model->get_all_kategori();
        // $this->load->view('barang',$kategori);
        $data['_view'] = 'barang/add';
        if ($this->session->userdata("level") == 'admin') {
            $this->load->view('layouts/main', $data);
        } else {
            $this->load->view('layouts/main_user', $data);
        }
    }

    private function _uploadImage()
    {
        $config['upload_path']          = 'resources/img/barang/';
        $config['allowed_types']        = 'gif|jpg|png';
        $config['file_name']            = $this->input->post('id_merk') . '-' . $this->input->post('nm_barang');
        $config['overwrite']            = true;
        $config['max_size']             = 1024; // 1MB
        $this->load->library('upload', $config);
        if ($this->upload->do_upload('foto')) {
            return $this->upload->data('file_name');
        }

        return null;
    }

    function add()
    {
        if (isset($_POST) && count($_POST) > 0) {
            $params = array(
                'id_kategori' => $this->input->post('id_kategori'),
                'id_merk' => $this->input->post('id_merk'),
                'nm_barang' => $this->input->post('nm_barang'),
                'id_satuan' => $this->input->post('id_satuan'),
                'stok' => $this->input->post('stok'),
                'tgl_masuk' => $this->input->post('tgl_masuk'),
                'id_ruangan' => $this->input->post('id_ruangan'),
                'foto' =>  $this->_uploadImage()
            );
            $barang_id = $this->Barang_model->add_barang($params);
            redirect('barang/index');
        } else {
            $data['kat'] = $this->Barang_model->get_all_kategori();
            // $data['merk'] = $this->Barang_model->get_all_merk();
            $data['satuan'] = $this->Barang_model->get_all_satuan();
            $data['ruangan'] = $this->Barang_model->get_all_ruangan();
            $data['_view'] = 'barang/add';
            if ($this->session->userdata("level") == 'admin') {
                $this->load->view('layouts/main', $data);
            } else {
                $this->load->view('layouts/main_user', $data);
            }
        }
    }

    /*
     * Editing a barang
     */
    function edit($id_barang)
    {
        // check if the barang exists before trying to edit it
        $data['barang'] = $this->Barang_model->get_barang($id_barang);

        if (isset($data['barang']['id_barang'])) {
            if (isset($_POST) && count($_POST) > 0) {
                $params = array(
                    'id_kategori' => $this->input->post('id_kategori'),
                    'id_merk' => $this->input->post('id_merk'),
                    'nm_barang' => $this->input->post('nm_barang'),
                    'id_satuan' => $this->input->post('id_satuan'),
                    'stok' => $this->input->post('stok'),
                    'tgl_masuk' => $this->input->post('tgl_masuk'),
                    'id_ruangan' => $this->input->post('id_ruangan'),
                    'foto' =>  $this->_uploadImage()
                );

                $this->Barang_model->update_barang($id_barang, $params);
                redirect('barang/index');
            } else {
                $data['kat'] = $this->Barang_model->get_all_kategori();
                $data['merk'] = $this->Barang_model->get_merk_kat($this->input->post('id_kategori'));
                $data['satuan'] = $this->Barang_model->get_all_satuan();
                $data['ruangan'] = $this->Barang_model->get_all_ruangan();
                $data['_view'] = 'barang/edit';
                if ($this->session->userdata("level") == 'admin') {
                    $this->load->view('layouts/main', $data);
                } else {
                    $this->load->view('layouts/main_user', $data);
                }
            }
        } else
            show_error('The barang you are trying to edit does not exist.');
    }

    /*
     * Deleting barang
     */
    function remove($id_barang)
    {
        $barang = $this->Barang_model->get_barang($id_barang);

        // check if the barang exists before trying to delete it
        if (isset($barang['id_barang'])) {
            $this->Barang_model->delete_barang($id_barang);
            redirect('barang/index');
        } else
            show_error('The barang you are trying to delete does not exist.');
    }
}
