<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Barang_masuk extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Barang_masuk_model');
    }

    /*
     * Listing of barang
     */
    function index()
    {
        if ($this->session->userdata("level") != NULL) {
            $jumlah_data = $this->Barang_masuk_model->jumlah_data();
            $config['base_url'] = base_url() . 'barang_masuk/index/';
            $config['total_rows'] = $jumlah_data;
            $config['per_page'] = 5;

            // Pagination link format 
            $config['num_tag_open'] = '<li>';
            $config['num_tag_close'] = '</li>';
            $config['cur_tag_open'] = '<li class="active"><a href="javascript:void(0);">';
            $config['cur_tag_close'] = '</a></li>';
            $config['next_link'] = 'Next';
            $config['prev_link'] = 'Prev';
            $config['next_tag_open'] = '<li class="pg-next">';
            $config['next_tag_close'] = '</li>';
            $config['prev_tag_open'] = '<li class="pg-prev">';
            $config['prev_tag_close'] = '</li>';
            $config['first_tag_open'] = '<li>';
            $config['first_tag_close'] = '</li>';
            $config['last_tag_open'] = '<li>';
            $config['last_tag_close'] = '</li>';

            $from = $this->uri->segment(3);
            $this->pagination->initialize($config);
            $data['barang_masuk'] = $this->Barang_masuk_model->get_all_barang_masuk($config['per_page'], $from);
            // $data['barang'] = $this->Barang_model->get_all_barang();

            $data['_view'] = 'barang_masuk/index';
            if ($this->session->userdata("level") == 'admin') {
                $this->load->view('layouts/main', $data);
            } else {
                $this->load->view('layouts/main_user', $data);
            }
        } else {
            $this->load->view('login/login');
        }
    }

    /*
     * Adding a new barang_masuk
     */

    function add()
    {
        if (isset($_POST) && count($_POST) > 0) {
            $params = array(
                'id_inventaris' => $this->Barang_masuk_model->get_kd_inv($this->input->post('id_barang')),
                'id_barang' => $this->input->post('id_barang'),
                'ket_kondisi' => $this->input->post('ket_kondisi'),
                'id_ruangan' => $this->input->post('id_ruangan'),
            );
            $barang_masuk_id = $this->Barang_masuk_model->add_barang_masuk($params);
            redirect('barang_masuk/index');
        } else {
            $data['ruangan'] = $this->Barang_masuk_model->get_all_ruangan();
            $data['barang'] = $this->Barang_masuk_model->get_all_barang();
            //  $data['kode'] = $this->Barang_masuk_model->get_kd_inv($this->input->post('id_barang'));
            $data['_view'] = 'barang_masuk/add';
            if ($this->session->userdata("level") == 'admin') {
                $this->load->view('layouts/main', $data);
            } else {
                $this->load->view('layouts/main_user', $data);
            }
        }
    }

    /*
     * Editing a barang_masuk
     */
    function edit($id_barang_masuk)
    {
        // check if the barang_masuk exists before trying to edit it
        $data['barang_masuk'] = $this->Barang_masuk_model->get_barang_masuk($id_barang_masuk);

        if (isset($data['barang_masuk']['id'])) {
            if (isset($_POST) && count($_POST) > 0) {
                $params = array(
                    'id_inventaris' => $this->input->post('id_inventaris'),
                    'id_barang' => $this->input->post('id_barang'),
                    'ket_kondisi' => $this->input->post('ket_kondisi'),
                    'id_ruangan' => $this->input->post('id_ruangan'),
                );

                $this->Barang_masuk_model->update_barang_masuk($id_barang_masuk, $params);
                redirect('barang_masuk/index');
            } else {
                $data['ruangan'] = $this->Barang_masuk_model->get_all_ruangan();
                $data['barang'] = $this->Barang_masuk_model->get_all_barang();
                $data['_view'] = 'barang_masuk/edit';
                if ($this->session->userdata("level") == 'admin') {
                    $this->load->view('layouts/main', $data);
                } else {
                    $this->load->view('layouts/main_user', $data);
                }
            }
        } else
            show_error('The barang_masuk you are trying to edit does not exist.');
    }

    /*
     * Deleting barang_masuk
     */
    function remove($id_barang_masuk)
    {
        $barang_masuk = $this->Barang_masuk_model->get_barang_masuk($id_barang_masuk);

        // check if the barang_masuk exists before trying to delete it
        if (isset($barang_masuk['id'])) {
            $this->Barang_masuk_model->delete_barang_masuk($id_barang_masuk);
            redirect('barang_masuk/index');
        } else
            show_error('The barang_masuk you are trying to delete does not exist.');
    }
}
