<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Kehilangan extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Kehilangan_model');
        $this->load->library('pdf');
    }

    /*
     * Listing of kehilangan
     */
    function index()
    {
        if ($this->session->userdata("level") != NULL) {
            $jumlah_data = $this->Kehilangan_model->jumlah_data();
            $config['base_url'] = base_url() . 'kehilangan/index/';
            $config['total_rows'] = $jumlah_data;
            $config['per_page'] = 10;

            // Pagination link format 
            $config['num_tag_open'] = '<li>';
            $config['num_tag_close'] = '</li>';
            $config['cur_tag_open'] = '<li class="active"><a href="javascript:void(0);">';
            $config['cur_tag_close'] = '</a></li>';
            $config['next_link'] = 'Next';
            $config['prev_link'] = 'Prev';
            $config['next_tag_open'] = '<li class="pg-next">';
            $config['next_tag_close'] = '</li>';
            $config['prev_tag_open'] = '<li class="pg-prev">';
            $config['prev_tag_close'] = '</li>';
            $config['first_tag_open'] = '<li>';
            $config['first_tag_close'] = '</li>';
            $config['last_tag_open'] = '<li>';
            $config['last_tag_close'] = '</li>';

            $from = $this->uri->segment(3);
            $this->pagination->initialize($config);
            $data['kehilangan'] = $this->Kehilangan_model->get_all_kehilangan($config['per_page'], $from);
            // $data['barang'] = $this->Barang_model->get_all_barang();

            $data['_view'] = 'kehilangan/index';
            if ($this->session->userdata("level") == 'admin') {
                $this->load->view('layouts/main', $data);
            } else {
                $this->load->view('layouts/main_user', $data);
            }
        } else {
            $this->load->view('login/login');
        }
    }

    /*
     * Adding a new kehilangan
     */

    function add()
    {
        if (isset($_POST) && count($_POST) > 0) {
            $params = array(
                'barang' => $this->input->post('barang'),
                'lokasi' => $this->input->post('lokasi'),
                'ket_barang' => $this->input->post('ket_barang'),
                'tgl_kehilangan' => $this->input->post('tgl_kehilangan'),
                'penemu' => $this->input->post('penemu'),
                'status' => 'belum',
            );

            $kehilangan_id = $this->Kehilangan_model->add_kehilangan($params);
            redirect('kehilangan/index');
        } else {
            $data['ruangan'] = $this->Kehilangan_model->get_all_ruangan();
            $data['_view'] = 'kehilangan/add';
            if ($this->session->userdata("level") == 'admin') {
                $this->load->view('layouts/main', $data);
            } else {
                $this->load->view('layouts/main_user', $data);
            }
        }
    }

    function cetak()
    {
        $tgl_awal = $this->input->post('tgl_awal');
        $tgl_ahir = $this->input->post('tgl_ahir');
        if ($tgl_awal != 0) {
            $pdf = new FPDF('P', 'mm', 'A4');
            // membuat halaman baru
            $pdf->AddPage();
            // setting jenis font yang akan digunakan
            $pdf->SetFont('Arial', 'B', 16);
            // mencetak string 
            $pdf->SetFont('Arial', 'B', 14);
            $pdf->Image('resources/img/poltek.png', 10, 6, 28);
            $pdf->Cell(190, 7, 'UPT SISTEM INFORMASI', 0, 1, 'C');
            $pdf->SetFont('Arial', 'B', 18);
            $pdf->Cell(190, 7, 'POLITEKNIK HARAPAN BERSAMA TEGAL', 0, 1, 'C');
            $pdf->SetFont('Arial', 'B', 12);
            $pdf->Cell(190, 7, 'LAPORAN KEHILANGAN BARANG', 0, 1, 'C');
            $pdf->SetFont('Arial', '', 9);
            $pdf->Cell(190, 6, 'Periode ' . date('d-m-Y', strtotime($tgl_awal)) . ' s/d ' . date('d-m-Y', strtotime($tgl_ahir)), 0, 1, 'C');

            // Memberikan space kebawah agar tidak terlalu rapat
            $pdf->Ln();
            $pdf->Cell(10, 7, '', 0, 1);
            $pdf->SetFont('Arial', 'B', 9);
            $pdf->Cell(10, 8, 'NO.', 1, 0, 'C');
            $pdf->Cell(30, 8, 'NAMA BARANG', 1, 0);
            $pdf->Cell(25, 8, 'LOKASI', 1, 0);
            $pdf->Cell(80, 8, 'KETERANGAN BARANG', 1, 0);
            $pdf->Cell(15, 8, 'STATUS', 1, 0, 'C');
            $pdf->Cell(30, 8, 'TGL. MASUK', 1, 1, 'C');
            $pdf->SetFont('Arial', '', 9);

            $barang = $this->db->select('*');
            $barang = $this->db->from('kehilangan a');
            $barang = $this->db->join('ruangan b', 'b.id_ruangan=a.lokasi', 'left');
            //$barang = $this->db->where('a.status',$stat);
            $barang = $this->db->where('a.tgl_kehilangan BETWEEN "' . date('Y-m-d', strtotime($tgl_awal)) . '" and "' . date('Y-m-d', strtotime($tgl_ahir)) . '"');

            $barang = $this->db->order_by('a.id_kehilangan', 'desc');
            $barang = $this->db->get()->result();
            $X = 0;
            foreach ($barang as $row) {
                $X += 1;
                $pdf->Cell(10, 6, $X, 1, 0, 'C');
                $pdf->Cell(30, 6, $row->barang, 1, 0);
                $pdf->Cell(25, 6, $row->lokasi, 1, 0);
                $pdf->Cell(80, 6, substr($row->ket_barang, 0, 53), 1, 0, 'L');
                $pdf->Cell(15, 6, $row->status, 1, 0, 'C');
                $pdf->Cell(30, 6, date("d-m-Y", strtotime($row->tgl_kehilangan)), 1, 1, 'C');
            }
            $pdf->Output();
        } else {
            $data['_view'] = 'kehilangan/cetak';
            if ($this->session->userdata("level") == 'admin') {
                $this->load->view('layouts/main', $data);
            } else {
                $this->load->view('layouts/main_user', $data);
            }
        }
    }

    function cetak_form($id_kehilangan)
    {
        $pdf = new FPDF('L', 'mm', 'A5');
        // membuat halaman baru
        $pdf->AddPage();
        // mencetak string 
        $pdf->SetFont('Arial', 'B', 12);
        $pdf->Image('resources/img/poltek.png', 10, 6, 25);
        $pdf->Cell(190, 7, 'UPT SISTEM INFORMASI', 0, 1, 'C');
        $pdf->SetFont('Arial', 'B', 14);
        $pdf->Cell(190, 7, 'POLITEKNIK HARAPAN BERSAMA TEGAL', 0, 1, 'C');
        $pdf->SetFont('Arial', 'B', 10);
        $pdf->Cell(190, 7, 'FORM PENGAMBILAN BARANG', 0, 1, 'C');

        $pdf->Ln();
        $pdf->Ln();
        $pdf->SetFont('Arial', '', 10);
        $pdf->Cell(190, 7, 'yang bertanda tangan dibawah ini:', 0, 1, 'L');
        $pdf->Cell(30, 7, 'Nama Lengkap', 0, 0, 'L');
        $pdf->Cell(30, 7, ': ................................................................', 0, 1, 'L');
        $pdf->Cell(30, 7, 'Kelas / Prodi', 0, 0, 'L');
        $pdf->Cell(30, 7, ': .......................... / ...................................', 0, 1, 'L');
        $pdf->Cell(30, 7, 'Telah mengambil barang berupa: ', 0, 0, 'L');
        $pdf->SetFont('Arial', '', 9);
        $pdf->Cell(10, 7, '', 0, 1);
        $pdf->SetFont('Arial', 'B', 9);
        $pdf->Cell(10, 8, 'NO.', 1, 0, 'C');
        $pdf->Cell(30, 8, 'NAMA BARANG', 1, 0);
        $pdf->Cell(25, 8, 'LOKASI', 1, 0, 'C');
        $pdf->Cell(95, 8, 'KETERANGAN BARANG', 1, 0);
        $pdf->Cell(25, 8, 'TGL. HILANG', 1, 1, 'C');

        $barang = $this->db->select('*');
        $barang = $this->db->from('kehilangan a');
        $barang = $this->db->join('ruangan b', 'b.id_ruangan=a.lokasi', 'left');
        //$barang = $this->db->where('a.status',$stat);
        $barang = $this->db->where('a.id_kehilangan =' . $id_kehilangan);
        $barang = $this->db->get()->result();

        $pdf->SetFont('Arial', '', 8);
        $X = 0;
        foreach ($barang as $row) {
            $X += 1;
            $pdf->Cell(10, 6, $X, 1, 0, 'C');
            $pdf->Cell(30, 6, $row->barang, 1, 0);
            $pdf->Cell(25, 6, $row->nm_ruangan, 1, 0);
            $pdf->Cell(95, 6, substr($row->ket_barang, 0, 53), 1, 0, 'L');
            $pdf->Cell(25, 6, date("d-M-Y", strtotime($row->tgl_kehilangan)), 1, 1, 'C');
        }

        $pdf->SetFont('Arial', '', 10);
        $pdf->Ln();
        $pdf->Cell(185, 6, 'Tegal, ' . date("d-M-Y"), 0, 1, 'R');
        $pdf->Ln();
        $pdf->Cell(95, 7, 'Petugas,', 0, 0, 'C');
        $pdf->Cell(95, 7, 'Penerima,', 0, 1, 'C');
        $pdf->Ln();
        $petugas = $this->session->userdata("nama");
        $pdf->Cell(95, 7, '( ' . $petugas . ' )', 0, 0, 'C');
        $pdf->Cell(95, 7, '(............................................)', 0, 1, 'C');
        $pdf->Output();
    }

    /*
     * Editing a kehilangan
     */
    function edit($id_kehilangan)
    {
        // check if the kehilangan exists before trying to edit it
        $data['kehilangan'] = $this->Kehilangan_model->get_kehilangan($id_kehilangan);

        if (isset($data['kehilangan']['id_kehilangan'])) {
            if (isset($_POST) && count($_POST) > 0) {
                $params = array(
                    'barang' => $this->input->post('barang'),
                    'lokasi' => $this->input->post('lokasi'),
                    'ket_barang' => $this->input->post('ket_barang'),
                    'tgl_kehilangan' => $this->input->post('tgl_kehilangan'),
                    'penemu' => $this->input->post('penemu'),
                    'status' => 'belum',
                );

                $this->Kehilangan_model->update_kehilangan($id_kehilangan, $params);
                redirect('kehilangan/index');
            } else {
                $data['ruangan'] = $this->Kehilangan_model->get_all_ruangan();
                $data['_view'] = 'kehilangan/edit';
                if ($this->session->userdata("level") == 'admin') {
                $this->load->view('layouts/main', $data);
            } else {
                $this->load->view('layouts/main_user', $data);
            }
            }
        } else
            show_error('The kehilangan you are trying to edit does not exist.');
    }

    function ambil($id_kehilangan)
    {
        // check if the kehilangan exists before trying to edit it
        $data['kehilangan'] = $this->Kehilangan_model->get_kehilangan($id_kehilangan);

        if (isset($data['kehilangan']['id_kehilangan'])) {
            if (isset($_POST) && count($_POST) > 0) {
                $params = array(
                    'barang' => $this->input->post('barang'),
                    'lokasi' => $this->input->post('lokasi'),
                    'ket_barang' => $this->input->post('ket_barang'),
                    'tgl_kehilangan' => $this->input->post('tgl_kehilangan'),
                    'penemu' => $this->input->post('penemu'),
                    'status' => 'ambil',
                );

                $this->Kehilangan_model->ambil_kehilangan($id_kehilangan, $params);
                redirect('kehilangan/index');
            } else {
                $data['ruangan'] = $this->Kehilangan_model->get_all_ruangan();
                $data['_view'] = 'kehilangan/ambil';
                if ($this->session->userdata("level") == 'admin') {
                $this->load->view('layouts/main', $data);
            } else {
                $this->load->view('layouts/main_user', $data);
            }
            }
        } else
            show_error('The kehilangan you are trying to edit does not exist.');
    }
    /*
     * Deleting kehilangan
     */
    function remove($id_kehilangan)
    {
        $kehilangan = $this->Kehilangan_model->get_kehilangan($id_kehilangan);

        // check if the kehilangan exists before trying to delete it
        if (isset($kehilangan['id_kehilangan'])) {
            $this->Kehilangan_model->delete_kehilangan($id_kehilangan);
            redirect('kehilangan/index');
        } else
            show_error('The kehilangan you are trying to delete does not exist.');
    }
}
