<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Kondisi extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        if (!$this->session->userdata("nama")) {
            $this->load->view('login/login');
        }
        $this->load->model('Kondisi_model');
    }

    /*
     * Listing of kondisi
     */
    function index()
    {
        $data['kondisi'] = $this->Kondisi_model->get_all_kondisi();

        $data['_view'] = 'kondisi/index';
        if ($this->session->userdata("level") == 'admin') {
                $this->load->view('layouts/main', $data);
            } else {
                $this->load->view('layouts/main_user', $data);
            }
    }

    /*
     * Adding a new kondisi
     */
    function add()
    {
        if (isset($_POST) && count($_POST) > 0) {
            $params = array(
                'nm_kondisi' => $this->input->post('nm_kondisi'),
            );

            $kondisi_id = $this->Kondisi_model->add_kondisi($params);
            redirect('kondisi/index');
        } else {
            $data['_view'] = 'kondisi/add';
            if ($this->session->userdata("level") == 'admin') {
                $this->load->view('layouts/main', $data);
            } else {
                $this->load->view('layouts/main_user', $data);
            }
        }
    }

    /*
     * Editing a kondisi
     */
    function edit($id_kondisi)
    {
        // check if the kondisi exists before trying to edit it
        $data['kondisi'] = $this->Kondisi_model->get_kondisi($id_kondisi);

        if (isset($data['kondisi']['id_kondisi'])) {
            if (isset($_POST) && count($_POST) > 0) {
                $params = array(
                    'nm_kondisi' => $this->input->post('nm_kondisi'),
                );

                $this->Kondisi_model->update_kondisi($id_kondisi, $params);
                redirect('kondisi/index');
            } else {
                $data['_view'] = 'kondisi/edit';
                if ($this->session->userdata("level") == 'admin') {
                $this->load->view('layouts/main', $data);
            } else {
                $this->load->view('layouts/main_user', $data);
            }
            }
        } else
            show_error('The kondisi you are trying to edit does not exist.');
    }

    /*
     * Deleting kondisi
     */
    function remove($id_kondisi)
    {
        $kondisi = $this->Kondisi_model->get_kondisi($id_kondisi);

        // check if the kondisi exists before trying to delete it
        if (isset($kondisi['id_kondisi'])) {
            $this->Kondisi_model->delete_kondisi($id_kondisi);
            redirect('kondisi/index');
        } else
            show_error('The kondisi you are trying to delete does not exist.');
    }
}
