<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Merk extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Merk_model');
    }

    /*
     * Listing of merk
     */
    function index()
    {
        if ($this->session->userdata("level")!=NULL) {
            $jumlah_data = $this->Merk_model->jumlah_data();
            $config['base_url'] = base_url() . 'merk/index/';
            $config['total_rows'] = $jumlah_data;
            $config['per_page'] = 10;

            // Pagination link format 
            $config['num_tag_open'] = '<li>';
            $config['num_tag_close'] = '</li>';
            $config['cur_tag_open'] = '<li class="active"><a href="javascript:void(0);">';
            $config['cur_tag_close'] = '</a></li>';
            $config['next_link'] = 'Next';
            $config['prev_link'] = 'Prev';
            $config['next_tag_open'] = '<li class="pg-next">';
            $config['next_tag_close'] = '</li>';
            $config['prev_tag_open'] = '<li class="pg-prev">';
            $config['prev_tag_close'] = '</li>';
            $config['first_tag_open'] = '<li>';
            $config['first_tag_close'] = '</li>';
            $config['last_tag_open'] = '<li>';
            $config['last_tag_close'] = '</li>';

            $from = $this->uri->segment(3);
            $this->pagination->initialize($config);
            $data['merk'] = $this->Merk_model->get_all_merk($config['per_page'], $from);
            // $data['barang'] = $this->Barang_model->get_all_barang();

            $data['_view'] = 'merk/index';
            if ($this->session->userdata("level") == 'admin') {
                $this->load->view('layouts/main', $data);
            } else {
                $this->load->view('layouts/main_user', $data);
            }
        } else {
            $this->load->view('login/login');
        }
    }

    /*
     * Adding a new merk
     */
    function add()
    {
        if (isset($_POST) && count($_POST) > 0) {
            $params = array(
                'nm_merk' => $this->input->post('nm_merk'),
            );

            $merk_id = $this->Merk_model->add_merk($params);
            redirect('merk/index');
        } else {
            $data['_view'] = 'merk/add';
            if ($this->session->userdata("level") == 'admin') {
                $this->load->view('layouts/main', $data);
            } else {
                $this->load->view('layouts/main_user', $data);
            }
        }
    }

    /*
     * Editing a merk
     */
    function edit($id_merk)
    {
        // check if the merk exists before trying to edit it
        $data['merk'] = $this->Merk_model->get_merk($id_merk);

        if (isset($data['merk']['id_merk'])) {
            if (isset($_POST) && count($_POST) > 0) {
                $params = array(
                    'nm_merk' => $this->input->post('nm_merk'),
                );

                $this->Merk_model->update_merk($id_merk, $params);
                redirect('merk/index');
            } else {
                $data['_view'] = 'merk/edit';
                if ($this->session->userdata("level") == 'admin') {
                $this->load->view('layouts/main', $data);
            } else {
                $this->load->view('layouts/main_user', $data);
            }
            }
        } else
            show_error('The merk you are trying to edit does not exist.');
    }

    /*
     * Deleting merk
     */
    function remove($id_merk)
    {
        $merk = $this->Merk_model->get_merk($id_merk);

        // check if the merk exists before trying to delete it
        if (isset($merk['id_merk'])) {
            $this->Merk_model->delete_merk($id_merk);
            redirect('merk/index');
        } else
            show_error('The merk you are trying to delete does not exist.');
    }
}
