<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Pengembalian extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Pengembalian_model');
        $this->load->library('pdf');
    }

    /*
     * Listing of barang
     */
    function index()
    {
        if ($this->session->userdata("level")!=NULL) {
            $jumlah_data = $this->Pengembalian_model->jumlah_data();
            $config['base_url'] = base_url() . 'pengembalian/index/';
            $config['total_rows'] = $jumlah_data;
            $config['per_page'] = 10;

            // Pagination link format 
            $config['num_tag_open'] = '<li>';
            $config['num_tag_close'] = '</li>';
            $config['cur_tag_open'] = '<li class="active"><a href="javascript:void(0);">';
            $config['cur_tag_close'] = '</a></li>';
            $config['next_link'] = 'Next';
            $config['prev_link'] = 'Prev';
            $config['next_tag_open'] = '<li class="pg-next">';
            $config['next_tag_close'] = '</li>';
            $config['prev_tag_open'] = '<li class="pg-prev">';
            $config['prev_tag_close'] = '</li>';
            $config['first_tag_open'] = '<li>';
            $config['first_tag_close'] = '</li>';
            $config['last_tag_open'] = '<li>';
            $config['last_tag_close'] = '</li>';

            $from = $this->uri->segment(3);
            $this->pagination->initialize($config);
            $data['pengembalian'] = $this->Pengembalian_model->get_all_pengembalian($config['per_page'], $from);
            // $data['barang'] = $this->Barang_model->get_all_barang();

            $data['_view'] = 'pengembalian/index';
            if ($this->session->userdata("level") == 'admin') {
                $this->load->view('layouts/main', $data);
            } else {
                $this->load->view('layouts/main_user', $data);
            }
        } else {
            $this->load->view('login/login');
        }
    }

    function cetak()
    {
        $tgl_awal = $this->input->post('tgl_awal');
        $tgl_ahir = $this->input->post('tgl_ahir');
        if ($tgl_awal != 0) {
            $pdf = new FPDF('P', 'mm', 'A4');
            // membuat halaman baru
            $pdf->AddPage();
            // setting jenis font yang akan digunakan
            $pdf->SetFont('Arial', 'B', 16);
            // mencetak string 
            $pdf->SetFont('Arial', 'B', 14);
            $pdf->Cell(190, 7, 'UPT SISTEM INFORMASI', 0, 1, 'C');
            $pdf->SetFont('Arial', 'B', 18);
            $pdf->Cell(190, 7, 'POLITEKNIK HARAPAN BERSAMA TEGAL', 0, 1, 'C');
            $pdf->SetFont('Arial', 'B', 12);
            $pdf->Cell(190, 7, 'LAPORAN PEMINJAMAN BARANG', 0, 1, 'C');
            $pdf->SetFont('Arial', '', 9);
            $pdf->Cell(190, 6, 'Periode ' . date('d-m-Y', strtotime($tgl_awal)) . ' s/d ' . date('d-m-Y', strtotime($tgl_ahir)), 0, 1, 'C');

            // Memberikan space kebawah agar tidak terlalu rapat
            $pdf->Ln();
            $pdf->Cell(10, 7, '', 0, 1);
            $pdf->SetFont('Arial', 'B', 9);
            $pdf->Cell(10, 6, 'NO.', 1, 0, 'C');
            $pdf->Cell(60, 6, 'NAMA PEMINJAM', 1, 0);
            $pdf->Cell(25, 6, 'KELAS', 1, 0);
            $pdf->Cell(40, 6, 'BARANG', 1, 0);
            $pdf->Cell(20, 6, 'JML', 1, 0, 'C');
            $pdf->Cell(35, 6, 'TGL. PENGEMBALIAN', 1, 1, 'C');
            $pdf->SetFont('Arial', '', 9);

            $barang = $this->db->select('*');
            $barang = $this->db->from('peminjaman a');
            $barang = $this->db->join('barang b', 'b.id_barang=a.id_barang', 'left');
            $barang = $this->db->join('user c', 'c.id_user=a.id_user', 'left');
            $barang = $this->db->join('kelas d', 'd.id_kelas=a.kelas', 'left');
            $barang = $this->db->where('a.tgl_kembali BETWEEN "' . date('Y-m-d', strtotime($tgl_awal)) . '" and "' . date('Y-m-d', strtotime($tgl_ahir)) . '"');
            $barang = $this->db->order_by('a.id_peminjaman', 'desc');
            $barang = $this->db->get()->result();
            $X = 0;
            foreach ($barang as $row) {
                $X += 1;
                $pdf->Cell(10, 6, $X, 1, 0, 'C');
                $pdf->Cell(60, 6, $row->nama_peminjam, 1, 0);
                $pdf->Cell(25, 6, $row->nm_kelas, 1, 0);
                $pdf->Cell(40, 6, $row->nm_barang, 1, 0);
                $pdf->Cell(20, 6, $row->jumlah, 1, 0, 'C');
                $pdf->Cell(35, 6, date("d-m-Y", strtotime($row->tgl_kembali)), 1, 1, 'C');
            }
            $pdf->Output();
        } else {
            $data['_view'] = 'pengembalian/cetak';
            if ($this->session->userdata("level") == 'admin') {
                $this->load->view('layouts/main', $data);
            } else {
                $this->load->view('layouts/main_user', $data);
            }
        }
    }
    /*
     * Adding a new pengembalian
     */

    function add()
    {
        if (isset($_POST) && count($_POST) > 0) {
            $params = array(
                'nama_peminjam' => $this->input->post('nama_peminjam'),
                'kelas' => $this->input->post('kelas'),
                'id_barang' => $this->input->post('id_barang'),
                'jumlah' => $this->input->post('jumlah'),
                'tgl_pinjam' => $this->input->post('tgl_pinjam'),
                'tgl_kembali' => $this->input->post('tgl_kembali'),
                'keterangan' => $this->input->post('keterangan'),
                'status' => $this->input->post('status'),
                'id_user' => $this->input->post('id_user'),
            );
            $pengembalian_id = $this->Pengembalian_model->add_pengembalian($params);
            redirect('pengembalian/index');
        } else {
            $data['kelas'] = $this->Pengembalian_model->get_all_kelas();
            $data['barang'] = $this->Pengembalian_model->get_all_barang();
            $data['_view'] = 'pengembalian/add';
            if ($this->session->userdata("level") == 'admin') {
                $this->load->view('layouts/main', $data);
            } else {
                $this->load->view('layouts/main_user', $data);
            }
        }
    }

    /*
     * Editing a pengembalian
     */
    function edit($id_pengembalian)
    {
        // check if the pengembalian exists before trying to edit it
        $data['pengembalian'] = $this->Pengembalian_model->get_pengembalian($id_pengembalian);

        if (isset($data['pengembalian']['id_peminjaman'])) {
            if (isset($_POST) && count($_POST) > 0) {
                $params = array(
                    'nama_peminjam' => $this->input->post('nama_peminjam'),
                    'kelas' => $this->input->post('kelas'),
                    'id_barang' => $this->input->post('id_barang'),
                    'jumlah' => $this->input->post('jumlah'),
                    'tgl_pinjam' => $this->input->post('tgl_pinjam'),
                    'tgl_kembali' => $this->input->post('tgl_kembali'),
                    'keterangan' => $this->input->post('keterangan'),
                    'status' => $this->input->post('status'),
                    'id_user' => $this->input->post('id_user'),
                );

                $this->Pengembalian_model->update_pengembalian($id_pengembalian, $params);
                redirect('pengembalian/index');
            } else {
                $data['kelas'] = $this->Pengembalian_model->get_all_kelas();
                $data['barang'] = $this->Pengembalian_model->get_all_barang();
                $data['_view'] = 'pengembalian/edit';
                if ($this->session->userdata("level") == 'admin') {
                $this->load->view('layouts/main', $data);
            } else {
                $this->load->view('layouts/main_user', $data);
            }
            }
        } else
            show_error('The pengembalian you are trying to edit does not exist.');
    }

    /*
     * Deleting pengembalian
     */
    function remove($id_pengembalian)
    {
        $pengembalian = $this->Pengembalian_model->get_pengembalian($id_pengembalian);

        // check if the pengembalian exists before trying to delete it
        if (isset($pengembalian['id_peminjaman'])) {
            $this->Pengembalian_model->delete_pengembalian($id_pengembalian);
            redirect('pengembalian/index');
        } else
            show_error('The pengembalian you are trying to delete does not exist.');
    }
}
