<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Perawatan extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Perawatan_model');
    }

    /*
     * Listing of barang
     */
    function index()
    {
        if ($this->session->userdata("level")!=NULL) {
            $jumlah_data = $this->Perawatan_model->jumlah_data();
            $config['base_url'] = base_url() . 'perawatan/index/';
            $config['total_rows'] = $jumlah_data;
            $config['per_page'] = 10;

            // Pagination link format 
            $config['num_tag_open'] = '<li>';
            $config['num_tag_close'] = '</li>';
            $config['cur_tag_open'] = '<li class="active"><a href="javascript:void(0);">';
            $config['cur_tag_close'] = '</a></li>';
            $config['next_link'] = 'Next';
            $config['prev_link'] = 'Prev';
            $config['next_tag_open'] = '<li class="pg-next">';
            $config['next_tag_close'] = '</li>';
            $config['prev_tag_open'] = '<li class="pg-prev">';
            $config['prev_tag_close'] = '</li>';
            $config['first_tag_open'] = '<li>';
            $config['first_tag_close'] = '</li>';
            $config['last_tag_open'] = '<li>';
            $config['last_tag_close'] = '</li>';

            $from = $this->uri->segment(3);
            $this->pagination->initialize($config);
            $data['perawatan'] = $this->Perawatan_model->get_all_perawatan($config['per_page'], $from);
            // $data['barang'] = $this->Barang_model->get_all_barang();

            $data['_view'] = 'perawatan/index';
            if ($this->session->userdata("level") == 'admin') {
                $this->load->view('layouts/main', $data);
            } else {
                $this->load->view('layouts/main_user', $data);
            }
        } else {
            $this->load->view('login/login');
        }
    }

    /*
     * Adding a new perawatan
     */

    function add()
    {
        if (isset($_POST) && count($_POST) > 0) {
            $params = array(
                'id_inventaris' => $this->input->post('id_inventaris'),
                'tgl_perawatan' => date('Y-m-d', strtotime($this->input->post('tgl_perawatan'))),
                'kondisi' => $this->input->post('id_kondisi'),
                'id_cek' => $this->input->post('id_cek'),
                'diagnosa' => $this->input->post('diagnosa'),
            );
            $perawatan_id = $this->Perawatan_model->add_perawatan($params);
            redirect('perawatan/index');
        } else {
            $data['kondisi'] = $this->Perawatan_model->get_all_kondisi();
            $data['user'] = $this->Perawatan_model->get_all_user();
            $data['inventaris'] = $this->Perawatan_model->get_all_inventaris();
            $data['_view'] = 'perawatan/add';
            if ($this->session->userdata("level") == 'admin') {
                $this->load->view('layouts/main', $data);
            } else {
                $this->load->view('layouts/main_user', $data);
            }
        }
    }

    /*
     * Editing a perawatan
     */
    function edit($id_perawatan)
    {
        // check if the perawatan exists before trying to edit it
        $data['perawatan'] = $this->Perawatan_model->get_perawatan($id_perawatan);

        if (isset($data['perawatan']['id_perawatan'])) {
            if (isset($_POST) && count($_POST) > 0) {
                $params = array(
                    'id_inventaris' => $this->input->post('id_inventaris'),
                    'tgl_perawatan' => $this->input->post('tgl_perawatan'),
                    'kondisi' => $this->input->post('id_kondisi'),
                    'id_cek' => $this->input->post('id_cek'),
                    'diagnosa' => $this->input->post('diagnosa'),
                );

                $this->Perawatan_model->update_perawatan($id_perawatan, $params);
                redirect('perawatan/index');
            } else {
                $data['kondisi'] = $this->Perawatan_model->get_all_kondisi();
                $data['user'] = $this->Perawatan_model->get_all_user();
                $data['inventaris'] = $this->Perawatan_model->get_all_inventaris();
                $data['_view'] = 'perawatan/edit';
                if ($this->session->userdata("level") == 'admin') {
                $this->load->view('layouts/main', $data);
            } else {
                $this->load->view('layouts/main_user', $data);
            }
            }
        } else
            show_error('The perawatan you are trying to edit does not exist.');
    }

    /*
     * Deleting perawatan
     */
    function remove($id_perawatan)
    {
        $perawatan = $this->Perawatan_model->get_perawatan($id_perawatan);

        // check if the perawatan exists before trying to delete it
        if (isset($perawatan['id_perawatan'])) {
            $this->Perawatan_model->delete_perawatan($id_perawatan);
            redirect('perawatan/index');
        } else
            show_error('The perawatan you are trying to delete does not exist.');
    }
}
