<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Profil extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Profil_model');
    }

    /*
     * Listing of profil
     */
    function index()
    {
        if ($this->session->userdata("level")==NULL) {
            $this->load->view('login/login');
        } else {
            $data['profil'] = $this->Profil_model->get_profil($this->session->userdata("id_user"));

            $data['_view'] = 'profil/index';
            if ($this->session->userdata("level") == 'admin') {
                $this->load->view('layouts/main', $data);
            } else {
                $this->load->view('layouts/main_user', $data);
            }
        }
    }

    /*
     * Adding a new profil
     */
    function add()
    {
        if (isset($_POST) && count($_POST) > 0) {
            $params = array(
                'password' => $this->input->post('password'),
                'nama' => $this->input->post('nama'),
                'foto' => $this->input->post('foto'),
                'profilname' => $this->input->post('profilname'),
                'level' => $this->input->post('level'),
            );

            $profil_id = $this->Profil_model->add_profil($params);
            redirect('profil/index');
        } else {
            $data['_view'] = 'profil/add';
            if ($this->session->userdata("level") == 'admin') {
                $this->load->view('layouts/main', $data);
            } else {
                $this->load->view('layouts/main_user', $data);
            }
        }
    }

    /*
     * Editing a profil
     */
    function edit($id_profil)
    {
        // check if the profil exists before trying to edit it
        $data['profil'] = $this->Profil_model->get_profil($id_profil);

        if (isset($data['profil']['id_profil'])) {
            if (isset($_POST) && count($_POST) > 0) {
                $params = array(
                    'password' => $this->input->post('password'),
                    'nama' => $this->input->post('nama'),
                    'foto' => $this->input->post('foto'),
                    'profilname' => $this->input->post('profilname'),
                    'level' => $this->input->post('level'),
                );

                $this->Profil_model->update_profil($id_profil, $params);
                redirect('profil/index');
            } else {
                $data['_view'] = 'profil/edit';
                if ($this->session->userdata("level") == 'admin') {
                $this->load->view('layouts/main', $data);
            } else {
                $this->load->view('layouts/main_user', $data);
            }
            }
        } else
            show_error('The profil you are trying to edit does not exist.');
    }

    /*
     * Deleting profil
     */
    function remove($id_profil)
    {
        $profil = $this->Profil_model->get_profil($id_profil);

        // check if the profil exists before trying to delete it
        if (isset($profil['id_profil'])) {
            $this->Profil_model->delete_profil($id_profil);
            redirect('profil/index');
        } else
            show_error('The profil you are trying to delete does not exist.');
    }
}
