<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Ruangan extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Ruangan_model');
    }

    /*
     * Listing of tb_barang
     */
    function index()
    {
        if ($this->session->userdata("level")!=NULL) {
            $jumlah_data = $this->Ruangan_model->jumlah_data();
            $config['base_url'] = base_url() . 'ruangan/index/';
            $config['total_rows'] = $jumlah_data;
            $config['per_page'] = 10;

            // Pagination link format 
            $config['num_tag_open'] = '<li>';
            $config['num_tag_close'] = '</li>';
            $config['cur_tag_open'] = '<li class="active"><a href="javascript:void(0);">';
            $config['cur_tag_close'] = '</a></li>';
            $config['next_link'] = 'Next';
            $config['prev_link'] = 'Prev';
            $config['next_tag_open'] = '<li class="pg-next">';
            $config['next_tag_close'] = '</li>';
            $config['prev_tag_open'] = '<li class="pg-prev">';
            $config['prev_tag_close'] = '</li>';
            $config['first_tag_open'] = '<li>';
            $config['first_tag_close'] = '</li>';
            $config['last_tag_open'] = '<li>';
            $config['last_tag_close'] = '</li>';

            $from = $this->uri->segment(3);
            $this->pagination->initialize($config);
            $data['ruangan'] = $this->Ruangan_model->get_all_ruangan($config['per_page'], $from);
            // $data['barang'] = $this->Barang_model->get_all_barang();

            $data['_view'] = 'ruangan/index';
            if ($this->session->userdata("level") == 'admin') {
                $this->load->view('layouts/main', $data);
            } else {
                $this->load->view('layouts/main_user', $data);
            }
        } else {
            $this->load->view('login/login');
        }
    }

    /*
     * Adding a new tb_barang
     */
    function add()
    {
        if (isset($_POST) && count($_POST) > 0) {
            $params = array(
                'nm_ruangan' => $this->input->post('nm_ruangan'),
                'lokasi_ruangan' => $this->input->post('lokasi_ruangan'),
            );

            $id_ruangan = $this->Ruangan_model->add_ruangan($params);
            redirect('ruangan/index');
        } else {
            $data['_view'] = 'ruangan/add';
            if ($this->session->userdata("level") == 'admin') {
                $this->load->view('layouts/main', $data);
            } else {
                $this->load->view('layouts/main_user', $data);
            }
        }
    }

    /*
     * Editing a tb_barang
     */
    function edit($id_ruangan)
    {
        // check if the tb_barang exists before trying to edit it
        $data['ruangan'] = $this->Ruangan_model->get_ruangan($id_ruangan);

        if (isset($data['ruangan']['id_ruangan'])) {
            if (isset($_POST) && count($_POST) > 0) {
                $params = array(
                    'id_ruangan' => $this->input->post('id_ruangan'),
                    'nm_ruangan' => $this->input->post('nm_ruangan'),
                    'lokasi_ruangan' => $this->input->post('lokasi_ruangan'),
                );

                $this->Ruangan_model->update_ruangan($id_ruangan, $params);
                redirect('ruangan/index');
            } else {
                $data['_view'] = 'ruangan/edit';
                if ($this->session->userdata("level") == 'admin') {
                $this->load->view('layouts/main', $data);
            } else {
                $this->load->view('layouts/main_user', $data);
            }
            }
        } else
            show_error('The ruangan you are trying to edit does not exist.');
    }

    /*
     * Deleting tb_barang
     */
    function remove($id_ruangan)
    {
        $ruangan = $this->Ruangan_model->get_ruangan($id_ruangan);

        // check if the tb_barang exists before trying to delete it
        if (isset($ruangan['id_ruangan'])) {
            $this->Ruangan_model->delete_ruangan($id_ruangan);
            redirect('ruangan/index');
        } else
            show_error('The ruangan you are trying to delete does not exist.');
    }
}
