<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tb_pengeluaran extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tb_pengeluaran_model');
    } 

    /*
     * Listing of tb_pengeluaran
     */
    function index()
    {
        $data['tb_pengeluaran'] = $this->Tb_pengeluaran_model->get_all_tb_pengeluaran();
        
        $data['_view'] = 'tb_pengeluaran/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new tb_pengeluaran
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'tgl_keluar' => $this->input->post('tgl_keluar'),
				'id_barang' => $this->input->post('id_barang'),
				'petugas' => $this->input->post('petugas'),
				'keterangan' => $this->input->post('keterangan'),
            );
            
            $tb_pengeluaran_id = $this->Tb_pengeluaran_model->add_tb_pengeluaran($params);
            redirect('tb_pengeluaran/index');
        }
        else
        {            
            $data['_view'] = 'tb_pengeluaran/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a tb_pengeluaran
     */
    function edit($id_pengeluaran)
    {   
        // check if the tb_pengeluaran exists before trying to edit it
        $data['tb_pengeluaran'] = $this->Tb_pengeluaran_model->get_tb_pengeluaran($id_pengeluaran);
        
        if(isset($data['tb_pengeluaran']['id_pengeluaran']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'tgl_keluar' => $this->input->post('tgl_keluar'),
					'id_barang' => $this->input->post('id_barang'),
					'petugas' => $this->input->post('petugas'),
					'keterangan' => $this->input->post('keterangan'),
                );

                $this->Tb_pengeluaran_model->update_tb_pengeluaran($id_pengeluaran,$params);            
                redirect('tb_pengeluaran/index');
            }
            else
            {
                $data['_view'] = 'tb_pengeluaran/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The tb_pengeluaran you are trying to edit does not exist.');
    } 

    /*
     * Deleting tb_pengeluaran
     */
    function remove($id_pengeluaran)
    {
        $tb_pengeluaran = $this->Tb_pengeluaran_model->get_tb_pengeluaran($id_pengeluaran);

        // check if the tb_pengeluaran exists before trying to delete it
        if(isset($tb_pengeluaran['id_pengeluaran']))
        {
            $this->Tb_pengeluaran_model->delete_tb_pengeluaran($id_pengeluaran);
            redirect('tb_pengeluaran/index');
        }
        else
            show_error('The tb_pengeluaran you are trying to delete does not exist.');
    }
    
}
