<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Asisten_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tb_barang by id_asisten
     */
    function get_asisten($id_asisten)
    {
        return $this->db->get_where('asisten',array('id_asisten'=>$id_asisten))->row_array();
    }
        
    /*
     * Get all tb_barang
     */
    function get_all_asisten($number,$offset)
    {
        $this->db->order_by('id_asisten', 'desc');
        $this->db->limit($number,$offset);       
        return $this->db->get('asisten')->result_array();
    }
        
    function data($number,$offset){
		return $query = $this->db->get('asisten',$number,$offset)->result();		
	}
 
	function jumlah_data(){
		return $this->db->get('asisten')->num_rows();
	}
    /*
     * function to add new tb_barang
     */
    function add_asisten($params)
    {
        $this->db->insert('asisten',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tb_barang
     */
    function update_asisten($id_asisten,$params)
    {
        $this->db->where('id_asisten',$id_asisten);
        return $this->db->update('asisten',$params);
    }
    
    /*
     * function to delete tb_barang
     */
    function delete_asisten($id_asisten)
    {
        return $this->db->delete('asisten',array('id_asisten'=>$id_asisten));
    }
}
