<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Barang_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    function get_barang($id_barang)
    {
        return $this->db->get_where('barang', array('id_barang' => $id_barang))->row_array();
    }
    function data($number, $offset)
    {
        return $query = $this->db->get('barang', $number, $offset)->result();
    }

    function jumlah_data()
    {
        return $this->db->get('barang')->num_rows();
    }

    function jumlah_data_by($keyword)
    {
        $this->db->select('*');
        $this->db->from('barang a');
        $this->db->join('kategori b', 'b.id_kategori=a.id_kategori', 'left');
        $this->db->join('merk c', 'c.id_merk=a.id_merk', 'left');
        $this->db->join('satuan d', 'd.id_satuan=a.id_satuan', 'left');
        $this->db->join('ruangan e', 'e.id_ruangan=a.id_ruangan', 'left');
        $this->db->like('a.nm_barang', $keyword);
        $this->db->order_by('a.id_barang', 'asc');
        $query = $this->db->get();
        return $query->num_rows();
    }
    /*
     * Get all barang
     */
    function get_all_barang($number, $offset)
    {
        $this->db->select('*');
        $this->db->from('barang a');
        $this->db->join('kategori b', 'b.id_kategori=a.id_kategori', 'left');
        $this->db->join('merk c', 'c.id_merk=a.id_merk', 'left');
        $this->db->join('satuan d', 'd.id_satuan=a.id_satuan', 'left');
        $this->db->join('ruangan e', 'e.id_ruangan=a.id_ruangan', 'left');
        //$this->db->where('c.album_id',$id);
        $this->db->order_by('a.id_barang', 'asc');
        $this->db->limit($number, $offset);
        $query = $this->db->get();
        return $query->result_array();

        //    $this->db->order_by('id_barang', 'desc');
        //    return $this->db->get('barang')->result_array();
    }

    function search($number, $offset, $keyword)
    {
        $this->db->select('*');
        $this->db->from('barang a');
        $this->db->join('kategori b', 'b.id_kategori=a.id_kategori', 'left');
        $this->db->join('merk c', 'c.id_merk=a.id_merk', 'left');
        $this->db->join('satuan d', 'd.id_satuan=a.id_satuan', 'left');
        $this->db->join('ruangan e', 'e.id_ruangan=a.id_ruangan', 'left');
        $this->db->like('a.nm_barang', $keyword);
        $this->db->order_by('a.id_barang', 'asc');
        $this->db->limit($number, $offset);
        $query = $this->db->get();
        return $query->result_array();

        //    $this->db->order_by('id_barang', 'desc');
        //    return $this->db->get('barang')->result_array();
    }
    /*
     * function to add new barang
     */
    function add_barang($params)
    {
        $this->db->insert('barang', $params);
        return $this->db->insert_id();
    }

    function get_all_kategori()
    {
        $this->db->order_by('nm_kategori', 'asc');
        return $this->db->get('kategori')->result_array();
    }

    function get_merk_kat($id_kat)
    {
        $this->db->select('*');
        $this->db->from('merk');
        $this->db->where('id_kategori', $id_kat);
        $this->db->order_by('nm_merk', 'asc');
        $query = $this->db->get();
        return $query->result_array();
    }

    function get_all_ruangan()
    {
        $this->db->order_by('nm_ruangan', 'asc');
        return $this->db->get('ruangan')->result_array();
    }
    function get_all_satuan()
    {
        $this->db->order_by('nm_satuan', 'asc');
        return $this->db->get('satuan')->result_array();
    }

    function get_satuan($id)
    {
        $this->db->select('*');
        $this->db->from('barang');
        $this->db->where('id_satuan', $id);
        $this->db->order_by('nm_barang', 'asc');
        $query = $this->db->get();
        return $query->result_array();
    }

    /*
     * function to update barang
     */
    function update_barang($id_barang, $params)
    {
        $this->db->where('id_barang', $id_barang);
        return $this->db->update('barang', $params);
    }

    function cetak()
    { }
    /*
     * function to delete barang
     */
    function delete_barang($id_barang)
    {
        return $this->db->delete('barang', array('id_barang' => $id_barang));
    }
}
