<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Barang_keluar_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    /*
     * Get tb_barang by id_barang
     */
    function get_barang_keluar($id_inventaris)
    {
        return $this->db->get_where('inventaris', array('id' => $id_inventaris))->row_array();
    }

    /*
     * Get all inventaris
     */
    function get_all_barang_keluar()
    {
        $this->db->select('*');
        $this->db->from('inventaris a');
        $this->db->join('barang b', 'b.id_barang=a.id_barang', 'left');
        $this->db->join('ruangan c', 'c.id_ruangan=a.id_ruangan', 'left');
        //$this->db->where('c.album_id',$id);
        $this->db->order_by('a.id', 'asc');
        $query = $this->db->get();
        return $query->result_array();

        //    $this->db->order_by('id_inventaris', 'desc');
        //    return $this->db->get('inventaris')->result_array();
    }

    /*
     * function to add new inventaris
     */
    function add_barang_keluar($params)
    {
        $this->db->insert('inventaris', $params);
        return $this->db->insert_id();
    }

    function get_all_barang()
    {
        $this->db->order_by('nm_barang', 'asc');
        return $this->db->get('barang')->result_array();
    }

    function get_all_ruangan()
    {
        $this->db->order_by('nm_ruangan', 'asc');
        return $this->db->get('ruangan')->result_array();
    }

    /*
     * function to update barang_keluar
     */
    function update_barang_keluar($id_barang_keluar, $params)
    {
        $this->db->where('id', $id_barang_keluar);
        return $this->db->update('inventaris', $params);
    }

    /*
     * function to delete barang_keluar
     */
    function delete_barang_keluar($id_barang_keluar)
    {
        return $this->db->delete('inventaris', array('id' => $id_barang_keluar));
    }
}
