<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Barang_masuk_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    /*
     * Get tb_barang by id_barang
     */
    function get_barang_masuk($id_inventaris)
    {
        return $this->db->get_where('inventaris', array('id' => $id_inventaris))->row_array();
    }

    function jumlah_data()
    {
        return $this->db->get('inventaris')->num_rows();
    }
    /*
     * Get all inventaris
     */
    function get_kd_inv($kode_barang)
    {
        $query = $this->db->query('Select MAX(RIGHT(id_inventaris,4)) AS no_urut from inventaris where id_barang = '.$kode_barang);
        //$this->db->from('inventaris a');
        //$this->db->join('barang b', 'b.id_barang=a.id_barang', 'left');
        //$this->db->join('ruangan c', 'c.id_ruangan=a.id_ruangan', 'left');
        //$this->db->where('b.id_barang', $kode_barang);
        //$this->db->order_by('id_inventaris', 'asc');
        //$query = $this->db->get();
        if ($query->num_rows() > 0) {
            foreach ($query->result() as $k) {
                $tmp = ((int) $k->no_urut) + 1;
                $kd = sprintf("%04s", $tmp);
            }
        } else {
            $kd = "0001";
        }
        date_default_timezone_set('Asia/Jakarta');
        $kdb = sprintf("%04s", $kode_barang);
        return $kdb . date('ym') . $kd;
    }

    function get_all_barang_masuk($number, $offset)
    {
        $this->db->select('*');
        $this->db->from('inventaris a');
        $this->db->join('barang b', 'b.id_barang=a.id_barang', 'left');
        $this->db->join('ruangan c', 'c.id_ruangan=a.id_ruangan', 'left');
        //$this->db->where('c.album_id',$id);
        $this->db->order_by('a.id', 'asc');
        $this->db->limit($number, $offset);
        $query = $this->db->get();
        return $query->result_array();

        //    $this->db->order_by('id_inventaris', 'desc');
        //    return $this->db->get('inventaris')->result_array();
    }

    /*
     * function to add new inventaris
     */
    function add_barang_masuk($params)
    {
        $this->db->insert('inventaris', $params);
        return $this->db->insert_id();
    }

    function get_all_barang()
    {
        $this->db->order_by('nm_barang', 'asc');
        return $this->db->get('barang')->result_array();
    }

    function get_all_ruangan()
    {
        $this->db->order_by('nm_ruangan', 'asc');
        return $this->db->get('ruangan')->result_array();
    }

    /*
     * function to update barang_masuk
     */
    function update_barang_masuk($id_barang_masuk, $params)
    {
        $this->db->where('id', $id_barang_masuk);
        return $this->db->update('inventaris', $params);
    }

    /*
     * function to delete barang_masuk
     */
    function delete_barang_masuk($id_barang_masuk)
    {
        return $this->db->delete('inventaris', array('id' => $id_barang_masuk));
    }
}
