<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Dashboard_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    /*
     * Get tb_barang by id_barang
     */
    function get_dashboard($id_dashboard)
    {
        return $this->db->get_where('dashboard', array('id_dashboard' => $id_dashboard))->row_array();
    }

    /*
     * Get all dashboard
     */

    /*
     * function to add new dashboard
     */
    function add_dashboard($params)
    {
        $this->db->insert('dashboard', $params);
        return $this->db->insert_id();
    }

    function get_all_barang()
    {
        $this->db->order_by('nm_barang', 'asc');
        return $this->db->get('barang')->num_rows();
    }

    function get_all_ruangan()
    {
        $this->db->order_by('nm_ruangan', 'asc');
        return $this->db->get('ruangan')->num_rows();
    }

    function get_all_peminjaman()
    {
        $this->db->select('*');
        $this->db->from('peminjaman');
        $this->db->where('status', 'Peminjaman');
        $this->db->order_by('id_peminjaman', 'desc');
        $query = $this->db->get();
        return $query->num_rows();
    }

    public function get_all_kehilangan()
    {
        $stat = "belum";
        $this->db->select('*');
        $this->db->from('kehilangan');
        $this->db->where('status', $stat);
        $this->db->order_by('id_kehilangan', 'desc');
        $query = $this->db->get();
        return $query->num_rows();
    }

    function get_all_asisten()
    {
        $this->db->order_by('id_asisten', 'desc');
        return $this->db->get('asisten')->result_array();
    }
    /*
     * function to update dashboard
     */
    function update_dashboard($id_dashboard, $params)
    {
        $this->db->where('id_dashboard', $id_dashboard);
        return $this->db->update('dashboard', $params);
    }

    /*
     * function to delete dashboard
     */
    function delete_dashboard($id_dashboard)
    {
        return $this->db->delete('dashboard', array('id_dashboard' => $id_dashboard));
    }
}
