<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Inventaris_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    /*
     * Get tb_barang by id_barang
     */
    function get_inventaris($id_inventaris)
    {
        return $this->db->get_where('inventaris', array('id_inventaris' => $id_inventaris))->row_array();
    }

    function data($number, $offset)
    {
        return $query = $this->db->get('barang', $number, $offset)->result();
    }

    function jumlah_data()
    {
        return $this->db->get('barang')->num_rows();
    }
    
    function jumlah_data_by($keyword)
    {
        $this->db->select('*');
        $this->db->from('inventaris a');
        $this->db->join('barang b', 'b.id_barang=a.id_barang', 'left');
        $this->db->join('ruangan c', 'c.id_ruangan=a.id_ruangan', 'left');
        //$this->db->where('c.album_id',$id);
        $this->db->like('a.id_inventaris', $keyword);
        $this->db->or_like('b.nm_barang', $keyword);
        $this->db->order_by('a.id_inventaris', 'asc');
        $query = $this->db->get();
        return $query->num_rows();
    }
    
    
    /*
     * Get all inventaris
     */
    function get_all_inventaris($number, $offset)
    {
        $this->db->select('*');
        $this->db->from('inventaris a');
        $this->db->join('barang b', 'b.id_barang=a.id_barang', 'left');
        $this->db->join('ruangan c', 'c.id_ruangan=a.id_ruangan', 'left');
        //$this->db->where('c.album_id',$id);
        $this->db->order_by('a.id_inventaris', 'asc');
        $this->db->limit($number, $offset);
        $query = $this->db->get();
        return $query->result_array();

        //    $this->db->order_by('id_inventaris', 'desc');
        //    return $this->db->get('inventaris')->result_array();
    }
    function search($number, $offset, $keyword)
    {
        $this->db->select('*');
        $this->db->from('inventaris a');
        $this->db->join('barang b', 'b.id_barang=a.id_barang', 'left');
        $this->db->join('ruangan c', 'c.id_ruangan=a.id_ruangan', 'left');
        //$this->db->where('c.album_id',$id);
        $this->db->like('a.id_inventaris', $keyword);
        $this->db->or_like('b.nm_barang', $keyword);
        $this->db->order_by('a.id_inventaris', 'asc');
        $this->db->limit($number, $offset);
        $query = $this->db->get();
        return $query->result_array();

        //    $this->db->order_by('id_barang', 'desc');
        //    return $this->db->get('barang')->result_array();
    }
    /*
     * function to add new inventaris
     */
    function add_inventaris($params)
    {
        $this->db->insert('inventaris', $params);
        return $this->db->insert_id();
    }

    function get_all_barang()
    {
        $this->db->order_by('nm_barang', 'asc');
        return $this->db->get('barang')->result_array();
    }

    function get_all_ruangan()
    {
        $this->db->order_by('nm_ruangan', 'asc');
        return $this->db->get('ruangan')->result_array();
    }

    /*
     * function to update inventaris
     */
    function update_inventaris($id_inventaris, $params)
    {
        $this->db->where('id_inventaris', $id_inventaris);
        return $this->db->update('inventaris', $params);
    }

    /*
     * function to delete inventaris
     */
    function delete_inventaris($id_inventaris)
    {
        return $this->db->delete('inventaris', array('id_inventaris' => $id_inventaris));
    }
}
