<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Kehilangan_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get kehilangan by id_kehilangan
     */
    function get_kehilangan($id_kehilangan)
    {
        return $this->db->get_where('kehilangan',array('id_kehilangan'=>$id_kehilangan))->row_array();
    }
        
    function data($number,$offset){
		return $query = $this->db->get('barang',$number,$offset)->result();		
	}
 
	function jumlah_data(){
		return $this->db->get('barang')->num_rows();
	}
    /*
     * Get all kehilangan
     */
	
    public function get_all_kehilangan($number,$offset)
    {
        $stat = "belum";
		$this->db->select('*');
    $this->db->from('kehilangan a');
    $this->db->join('ruangan b', 'b.id_ruangan=a.lokasi', 'left');
    $this->db->where('a.status',$stat);
    $this->db->order_by('a.id_kehilangan','desc'); 
    $this->db->limit($number,$offset);               
    $query = $this->db->get(); 
    return $query->result_array();
    }   
    /*
     * function to add new kehilangan
     */
    function add_kehilangan($params)
    {
        $this->db->insert('kehilangan',$params);
        return $this->db->insert_id();
    }
    
    function get_all_ruangan()
    {
        $this->db->order_by('nm_ruangan', 'asc');
        return $this->db->get('ruangan')->result_array();
    }
    /*
     * function to update kehilangan
     */
    function update_kehilangan($id_kehilangan,$params)
    {
        $this->db->where('id_kehilangan',$id_kehilangan);
        return $this->db->update('kehilangan',$params);
    }
    
    function ambil_kehilangan($id_kehilangan,$params)
    {
        $this->db->where('id_kehilangan',$id_kehilangan);
        return $this->db->update('kehilangan',$params);
    }
    /*
     * function to delete kehilangan
     */
    function delete_kehilangan($id_kehilangan)
    {
        return $this->db->delete('kehilangan',array('id_kehilangan'=>$id_kehilangan));
    }
}
