<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Merk_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tb_merk by id_merk
     */
    function get_merk($id_merk)
    {
        return $this->db->get_where('merk',array('id_merk'=>$id_merk))->row_array();
    }
        
    /*
     * Get all tb_merk
     */
    function get_kategori($id_kategori)
    {
        $this->db->select('*');
        $this->db->from('merk a');
        $this->db->join('kategori b', 'b.id_kategori=a.id_kategori', 'left');
        $this->db->like('a.nm_barang', $id_kategori);
        $this->db->order_by('a.id_kategori', 'asc');
        $query = $this->db->get();
        return $query->result_array();

        //    $this->db->order_by('id_barang', 'desc');
        //    return $this->db->get('barang')->result_array();
    }
    function data($number,$offset){
		return $query = $this->db->get('merk',$number,$offset)->result();		
	}
 
	function jumlah_data(){
		return $this->db->get('merk')->num_rows();
    }
    
    function get_all_merk($number,$offset)
    {
        $this->db->select('*');
        $this->db->from('merk a');
        $this->db->join('kategori b', 'b.id_kategori=a.id_kategori', 'left');
        $this->db->order_by('id_merk', 'desc');
        $this->db->limit($number,$offset);       
        return $this->db->get()->result_array();
    }
    
    function get_all_kategori()
    {
        $this->db->order_by('nm_kategori', 'asc');
        return $this->db->get('kategori')->result_array();
    }
    /*
     * function to add new tb_merk
     */
    function add_merk($params)
    {
        $this->db->insert('merk',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tb_merk
     */
    function update_merk($id_merk,$params)
    {
        $this->db->where('id_merk',$id_merk);
        return $this->db->update('merk',$params);
    }
    
    /*
     * function to delete tb_merk
     */
    function delete_merk($id_merk)
    {
        return $this->db->delete('merk',array('id_merk'=>$id_merk));
    }
}
