<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Peminjaman_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tb_barang by id_barang
     */
    function get_peminjaman($id_peminjaman)
    {
        return $this->db->get_where('peminjaman',array('id_peminjaman'=>$id_peminjaman))->row_array();
    }
      
    function data($number,$offset){
		return $query = $this->db->get('peminjaman',$number,$offset)->result();		
	}
 
	function jumlah_data(){
		return $this->db->get('peminjaman')->num_rows();
	}  
    /*
     * Get all peminjaman
     */
    function get_all_peminjaman($number,$offset)
    {
		$this->db->select('*');
    $this->db->from('peminjaman a'); 
    $this->db->join('barang b', 'b.id_barang=a.id_barang', 'left');
    $this->db->join('user c', 'c.id_user=a.id_user', 'left');
    $this->db->where('a.status','Peminjaman');
    $this->db->order_by('a.id_peminjaman','desc');  
    $this->db->limit($number,$offset);              
    $query = $this->db->get(); 
    return $query->result_array();
	
    //    $this->db->order_by('id_peminjaman', 'desc');
    //    return $this->db->get('peminjaman')->result_array();
    }
        
    /*
     * function to add new peminjaman
     */
    function add_peminjaman($params)
    {
        $this->db->insert('peminjaman',$params);
        return $this->db->insert_id();
    }
    
    function get_all_barang()
    {
        $this->db->order_by('nm_barang', 'asc');
        return $this->db->get('barang')->result_array();
    }
	
    function get_peminjaman_by()
    {
        $this->db->select('*');
        $this->db->from('peminjaman');
        $this->db->where('status', 'Peminjaman');
        $this->db->order_by('id_peminjaman', 'desc');
        $query = $this->db->get();
        return $query->num_rows();
    }

    function get_all_user()
    {
        $this->db->order_by('nm_user', 'asc');
        return $this->db->get('user')->result_array();
    }

    function get_all_kelas()
    {
        $this->db->order_by('nm_kelas', 'asc');
        return $this->db->get('kelas')->result_array();
    }
	
    /*
     * function to update peminjaman
     */
    function update_peminjaman($id_peminjaman,$params)
    {
        $this->db->where('id_peminjaman',$id_peminjaman);
        return $this->db->update('peminjaman',$params);
    }
    
    /*
     * function to delete peminjaman
     */
    function delete_peminjaman($id_peminjaman)
    {
        return $this->db->delete('peminjaman',array('id_peminjaman'=>$id_peminjaman));
    }
}
