<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Ruangan_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tb_barang by id_asisten
     */
    function get_ruangan($id_ruangan)
    {
        return $this->db->get_where('ruangan',array('id_ruangan'=>$id_ruangan))->row_array();
    }

    function data($number,$offset){
		return $query = $this->db->get('ruangan',$number,$offset)->result();		
	}
 
	function jumlah_data(){
		return $this->db->get('ruangan')->num_rows();
	}
    /*
     * Get all tb_barang
     */
    function get_all_ruangan($number,$offset)
    {
        $this->db->order_by('id_ruangan', 'desc'); 
        $this->db->limit($number,$offset);       
        return $this->db->get('ruangan')->result_array();
    }
        
    /*
     * function to add new tb_barang
     */
    function add_ruangan($params)
    {
        $this->db->insert('ruangan',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tb_barang
     */
    function update_ruangan($id_ruangan,$params)
    {
        $this->db->where('id_ruangan',$id_ruangan);
        return $this->db->update('ruangan',$params);
    }
    
    /*
     * function to delete tb_barang
     */
    function delete_ruangan($id_ruangan)
    {
        return $this->db->delete('ruangan',array('id_ruangan'=>$id_ruangan));
    }
}
