<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tb_pengeluaran_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tb_pengeluaran by id_pengeluaran
     */
    function get_tb_pengeluaran($id_pengeluaran)
    {
        return $this->db->get_where('tb_pengeluaran',array('id_pengeluaran'=>$id_pengeluaran))->row_array();
    }
        
    /*
     * Get all tb_pengeluaran
     */
    function get_all_tb_pengeluaran()
    {
        $this->db->order_by('id_pengeluaran', 'desc');
        return $this->db->get('tb_pengeluaran')->result_array();
    }
        
    /*
     * function to add new tb_pengeluaran
     */
    function add_tb_pengeluaran($params)
    {
        $this->db->insert('tb_pengeluaran',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tb_pengeluaran
     */
    function update_tb_pengeluaran($id_pengeluaran,$params)
    {
        $this->db->where('id_pengeluaran',$id_pengeluaran);
        return $this->db->update('tb_pengeluaran',$params);
    }
    
    /*
     * function to delete tb_pengeluaran
     */
    function delete_tb_pengeluaran($id_pengeluaran)
    {
        return $this->db->delete('tb_pengeluaran',array('id_pengeluaran'=>$id_pengeluaran));
    }
}
