<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tb_retur_suplier_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tb_retur_suplier by id_retur_suplier
     */
    function get_tb_retur_suplier($id_retur_suplier)
    {
        return $this->db->get_where('tb_retur_suplier',array('id_retur_suplier'=>$id_retur_suplier))->row_array();
    }
        
    /*
     * Get all tb_retur_suplier
     */
    function get_all_tb_retur_suplier()
    {
        $this->db->order_by('id_retur_suplier', 'desc');
        return $this->db->get('tb_retur_suplier')->result_array();
    }
        
    /*
     * function to add new tb_retur_suplier
     */
    function add_tb_retur_suplier($params)
    {
        $this->db->insert('tb_retur_suplier',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tb_retur_suplier
     */
    function update_tb_retur_suplier($id_retur_suplier,$params)
    {
        $this->db->where('id_retur_suplier',$id_retur_suplier);
        return $this->db->update('tb_retur_suplier',$params);
    }
    
    /*
     * function to delete tb_retur_suplier
     */
    function delete_tb_retur_suplier($id_retur_suplier)
    {
        return $this->db->delete('tb_retur_suplier',array('id_retur_suplier'=>$id_retur_suplier));
    }
}
