<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tb_retur_customer_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tb_retur_customer by id_retur_customer
     */
    function get_tb_retur_customer($id_retur_customer)
    {
        return $this->db->get_where('tb_retur_customer',array('id_retur_customer'=>$id_retur_customer))->row_array();
    }
        
    /*
     * Get all tb_retur_customer
     */
    function get_all_tb_retur_customer()
    {
        $this->db->order_by('id_retur_customer', 'desc');
        return $this->db->get('tb_retur_customer')->result_array();
    }
        
    /*
     * function to add new tb_retur_customer
     */
    function add_tb_retur_customer($params)
    {
        $this->db->insert('tb_retur_customer',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tb_retur_customer
     */
    function update_tb_retur_customer($id_retur_customer,$params)
    {
        $this->db->where('id_retur_customer',$id_retur_customer);
        return $this->db->update('tb_retur_customer',$params);
    }
    
    /*
     * function to delete tb_retur_customer
     */
    function delete_tb_retur_customer($id_retur_customer)
    {
        return $this->db->delete('tb_retur_customer',array('id_retur_customer'=>$id_retur_customer));
    }
}
